"""initial schema

Revision ID: 8a90b8cefc9e
Revises: 
Create Date: 2026-08-13 13:41:04.929296

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '8a90b8cefc9e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort_baseline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating_band', sa.String(length=16), nullable=False),
    sa.Column('time_control', sa.String(length=16), nullable=False),
    sa.Column('motif_type', sa.String(length=32), nullable=False),
    sa.Column('phase', sa.String(length=12), nullable=False),
    sa.Column('time_bucket', sa.String(length=16), nullable=False),
    sa.Column('error_rate', sa.Float(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('ci_low', sa.Float(), nullable=True),
    sa.Column('ci_high', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rating_band', 'time_control', 'motif_type', 'phase', 'time_bucket')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('current_rating', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'username')
    )
    op.create_table('position_eval',
    sa.Column('position_key', sa.String(length=100), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('eval_cp', sa.Integer(), nullable=True),
    sa.Column('mate_in', sa.Integer(), nullable=True),
    sa.Column('pv_moves', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('position_key', 'node_count')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('platform_game_id', sa.String(length=64), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_control', sa.String(length=32), nullable=True),
    sa.Column('player_color', sa.String(length=5), nullable=False),
    sa.Column('result', sa.String(length=8), nullable=True),
    sa.Column('opponent_rating', sa.Integer(), nullable=True),
    sa.Column('eco', sa.String(length=3), nullable=True),
    sa.Column('pgn', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'platform_game_id')
    )
    op.create_table('weakness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('motif_type', sa.String(length=32), nullable=False),
    sa.Column('phase', sa.String(length=12), nullable=True),
    sa.Column('time_bucket', sa.String(length=16), nullable=True),
    sa.Column('player_rate', sa.Float(), nullable=False),
    sa.Column('cohort_rate', sa.Float(), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=False),
    sa.Column('p_value', sa.Float(), nullable=False),
    sa.Column('q_value', sa.Float(), nullable=True),
    sa.Column('total_winprob_lost', sa.Float(), nullable=False),
    sa.Column('n_observations', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('move_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('san', sa.String(length=16), nullable=False),
    sa.Column('position_key', sa.String(length=100), nullable=False),
    sa.Column('win_prob_before', sa.Float(), nullable=True),
    sa.Column('win_prob_after', sa.Float(), nullable=True),
    sa.Column('delta_win_prob', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=12), nullable=True),
    sa.Column('best_move', sa.String(length=8), nullable=True),
    sa.Column('was_forced', sa.Boolean(), nullable=False),
    sa.Column('was_book', sa.Boolean(), nullable=False),
    sa.Column('phase', sa.String(length=12), nullable=True),
    sa.Column('clock_remaining_s', sa.Float(), nullable=True),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'ply')
    )
    op.create_table('motif',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('move_analysis_id', sa.Integer(), nullable=False),
    sa.Column('motif_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['move_analysis_id'], ['move_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motif')
    op.drop_table('move_analysis')
    op.drop_table('weakness')
    op.drop_table('game')
    op.drop_table('position_eval')
    op.drop_table('player')
    op.drop_table('cohort_baseline')
    # ### end Alembic commands ###
